server:
  http_listen_port: 9080  # Порт для HTTP-запросов

clients:
  - url: http://loki:3100/api/prom/push  # Адрес Loki для получения логов

positions:
  filename: /tmp/positions.yaml  # Позиции, где будет сохраняться текущее состояние логов

scrape_configs:
  - job_name: 'docker'
    docker_sd_configs:
      - host: unix:///var/run/docker.sock  # Указываем Docker сокет для отслеживания контейнеров
        refresh_interval: 10s  # Интервал обновления списка контейнеров

    pipeline_stages:
      - docker: {}  # Анализируем Docker логи

    relabel_configs:
      - source_labels: [__meta_docker_container_name]
        target_label: container_name
      - source_labels: [__meta_docker_container_name]
        target_label: job
        replacement: 'book-service'  # Настроим название job для book-service
      - target_label: __path__
        replacement: /var/log/docker/*log  # Указываем путь к логам Docker
