stages:
  - test-circle

variables:
  GRADLE_OPTS: -Dorg.gradle.daemon=false
  GRADLE_USER_HOME: ${CI_PROJECT_DIR}/.gradle

cache:
  paths:
    - .gradle/wrapper
    - .gradle/caches

test-circle:
  stage: test-circle
  image: gradle:8.6-jdk17
  variables:
    ITEMS: "server1 server2 server3"
  script:
    - |
      for item in $ITEMS; do
        echo "Деплоим $item"
        ./deploy.sh "$item"
      done