stages:
  - swagger-generate
  - docs-publish

variables:
  GRADLE_OPTS: -Dorg.gradle.daemon=false
  GRADLE_USER_HOME: ${CI_PROJECT_DIR}/.gradle

cache:
  paths:
    - .gradle/wrapper
    - .gradle/caches

swagger-generate:
  stage: swagger-generate
  image: gradle:8.6-jdk17
  artifacts:
    paths:
      - ./docs/**
  before_script:
    - chmod +x gradlew
  script:
    - ./gradlew generateOpenApiDocs


docs-publish:
  stage: docs-publish
  image: gradle:8.6-jdk17
  variables:
    OPENAPI_SOURCE: "docs/openapi.json"
    DOCS_SOURCE: "docs/docs.html"                         # Папка для HTML
    GITHUB_REPO: "sandress2998/MonitoringApp.git"     # Например, "myorg/monitoring-app"
    GITHUB_PAGES_BRANCH: "gh-pages"            # Ветка для GitHub Pages
  script:
    - git clone --branch ${GITHUB_PAGES_BRANCH} "https://${GITHUB_TOKEN}@github.com/${GITHUB_REPO}" MonitoringApp
    - cd MonitoringApp
    - mkdir -p docs
    - cp ../${DOCS_SOURCE} ./docs/index.html
    - cp ../${OPENAPI_SOURCE} ./docs/openapi.json
    - git config user.name "CI Bot" && git config user.email "ci@example.com"
    - git add ./docs && git commit --allow-empty -m "Update $(date +%Y-%m-%d)"
    - git push "https://${GITHUB_TOKEN}@github.com/${GITHUB_REPO}" ${GITHUB_PAGES_BRANCH}
  rules:
    - if: $CI_COMMIT_BRANCH == "master" || $CI_COMMIT_BRANCH == "main"