groups:
  - name: postgres-recordings
    interval: 30s  # Частота вычисления (рекомендуется 2-4x scrape_interval)
    rules:
      # 1. Среднее время выполнения запросов (перцентили)
      - record: pg:stat_statements:avg_time_seconds
        expr: avg(pg_stat_statements_mean_time_seconds) by (datname, queryid)

      # 2. Общее количество подключений по БД
      - record: pg:connections:total
        expr: sum(pg_stat_activity_count) by (datname)

      # 3. Активные подключения
      - record: pg:connections:active
        expr: sum(pg_stat_activity_count{state="active"}) by (datname)

      # 4. Загрузка БД (транзакции/сек)
      - record: pg:client_transactions:rate5m
        expr: |
          sum(
            rate(pg_stat_database_xact_commit{backend_type="client backend"}[5m])
            + rate(pg_stat_database_xact_rollback{backend_type="client backend"}[5m])
          ) by (datname)

      # 5. Размер БД в GB
      - record: pg:database:size_gb
        expr: pg_database_size_bytes / 1024 / 1024 / 1024

      # 6. Буферный кеш (хитрейт)
      - record: pg:buffer_cache:hit_ratio
        expr: (pg_stat_database_blks_hit - pg_stat_database_blks_read) / pg_stat_database_blks_hit * 100
        labels:
          type: "buffer_cache"

      # 7. Медленные запросы (>100ms)
      - record: pg:slow_queries:count
        expr: count(pg_stat_statements_mean_time_seconds > 0.1) by (datname)