pg_stat_client_transactions:
  query: |
    SELECT 
      datname,
      xact_commit as commits,
      xact_rollback as rollbacks
    FROM pg_stat_database
    WHERE datid IN (
      SELECT DISTINCT datid 
      FROM pg_stat_activity 
      WHERE 
        application_name = 'PostgreSQL JDBC Driver' AND
        state = 'idle' AND
        wait_event_type = 'Client'
    )
  metrics:
    - datname:
        usage: "LABEL"
        description: "Database name"
    - commits:
        usage: "COUNTER"
        description: "Client transactions committed"
    - rollbacks:
        usage: "COUNTER"
        description: "Client transactions rolled back"